apiVersion: apps/v1
kind: Deployment
metadata:
  name: synonym-dictionary
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synonym-dictionary
  template:
    metadata:
      labels:
        app: synonym-dictionary
    spec:
      containers:
      - name: synonym-dictionary
        image: shdkej/synonym-dictionary:0.0.2-prerelease34
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: synonym-dictionary
  namespace: default
  labels:
    app: synonym-dictionary
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: synonym-dictionary
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: synonym-dictionary
  namespace: default
spec:
  rules:
  - host: dict.minikube
    http:
      paths:
      - path: /
        backend:
          serviceName: synonym-dictionary
          servicePort: 8080
