FROM docker.elastic.co/elasticsearch/elasticsearch:7.7.0
WORKDIR /usr/share/elasticsearch/
COPY ./dictionary/synonyms.txt ./config/synonyms.txt
COPY ./dictionary/userdict.txt ./config/userdict.txt
WORKDIR /usr/share/elasticsearch/bin/
RUN elasticsearch-plugin install analysis-nori
ENV discovery.type=single-node
ENV cluster.name=docker-cluster
ENV ES_JAVA_OPTS="-Xms1g -Xmx1g"
