name: ci

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{steps.semver.outputs.version}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set docker image name env
        run: |
          #echo "DOCKER_IMAGE_NAME=shdkej/${{ github.event.repository.name }}" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_NAME=${{ github.repository }}" >> $GITHUB_ENV

      - name: Generate semantic tag
        uses: paulhatch/semantic-version@v4.0.2
        id: semver
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          format: "${major}.${minor}.${patch}-prerelease${increment}"

      - name: Set docker image tag env
        run: |
          echo ${{ steps.semver.outputs.version }}
          echo "DOCKER_TAG_VERSION=${{ steps.semver.outputs.version }}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG_VERSION }}
            ${{ env.DOCKER_IMAGE_NAME }}:latest

  updateK8s:
    name: updateK8s
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set docker image name env
      run: echo "DOCKER_IMAGE_NAME=${{ github.repository }}" >> $GITHUB_ENV

    - name: Set docker image tag env
      run: echo "DOCKER_TAG_VERSION=${{ needs.build.outputs.version }}" >> $GITHUB_ENV

    - name: Update Kubernetes resources
      env:
        DOCKER_IMAGE_NAME: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG_VERSION }}
      run: |
       cd deployments
       sed -i '/image/s/[^:]*$/${{ env.DOCKER_TAG_VERSION }}/' app.yml

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Update k8s resources (image version)"
        git tag ${{ env.DOCKER_TAG_VERSION }}

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tags: true

